include_directories(${CMAKE_CURRENT_LIST_DIR})

if (NOT DEFINED XARCHIVES_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../XArchive/xarchives.cmake)
    set(XGENERICARCHIVEWIDGET_SOURCES ${XGENERICARCHIVEWIDGET_SOURCES} ${XARCHIVES_SOURCES})
endif()

if (NOT DEFINED XSHORTCUTS_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../XShortcuts/xshortcuts.cmake)
    set(XGENERICARCHIVEWIDGET_SOURCES ${XGENERICARCHIVEWIDGET_SOURCES} ${XSHORTCUTS_SOURCES})
endif()

set(XGENERICARCHIVEWIDGET_SOURCES
    ${XGENERICARCHIVEWIDGET_SOURCES}
    ${CMAKE_CURRENT_LIST_DIR}/xgenericarchivewidget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xgenericarchivewidget.h
    ${CMAKE_CURRENT_LIST_DIR}/xgenericarchivewidget.ui
    )
